"""Apply Postgres Row-Level Security (RLS) tenant-isolation policies.

This is the authoritative, database-level backstop for multi-tenant isolation. The
application-layer regex scoper (app/core/tenant/connection.py) remains as a
convenience/defense-in-depth layer, but RLS is what makes cross-tenant reads and
writes *impossible* even if an app-layer query is written incorrectly.

Contract (set per-connection by app/core/db.py::_apply_rls_session):
  * GUC ``app.bypass_rls = 'on'``  -> cross-tenant access (raw conn, super-admin, offline).
  * GUC ``app.tenant_id = '<id>'`` -> scoped to one tenant when not bypassing.
  * Neither set                    -> no rows (fail closed).

IMPORTANT operational notes:
  * ``FORCE ROW LEVEL SECURITY`` is used so the policies apply even to the table owner.
  * A Postgres **superuser always bypasses RLS**. The application MUST connect as a
    normal (non-superuser) role, or isolation is silently disabled.

Usage:
  python tools/apply_rls.py --print          # emit SQL only (no DB connection)
  python tools/apply_rls.py                   # apply to $DATABASE_URL (must be Postgres)
  python tools/apply_rls.py --database-url postgresql://user:pass@host/db
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Allow running as a plain script (python tools/apply_rls.py) by putting the repo
# root on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

# Single source of truth for which tables are tenant-scoped.
from app.core.tenant.connection import SCOPED_TABLES

POLICY_NAME = "tenant_isolation"
_PREDICATE = (
    "current_setting('app.bypass_rls', true) = 'on'\n"
    "             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint"
)


def _table_block(table: str) -> str:
    return f"""DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = '{table}' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS {POLICY_NAME} ON {table};
    CREATE POLICY {POLICY_NAME} ON {table}
      USING ({_PREDICATE})
      WITH CHECK ({_PREDICATE});
  END IF;
END $$;"""


def generate_sql() -> str:
    header = (
        "-- Postgres Row-Level Security tenant-isolation policies.\n"
        "-- Generated by tools/apply_rls.py from SCOPED_TABLES. Idempotent; safe to re-run.\n"
        "-- Apply with: python tools/apply_rls.py   (or psql -f this file)\n"
    )
    blocks = [_table_block(table) for table in sorted(SCOPED_TABLES)]
    return header + "\n\n".join(blocks) + "\n"


def apply_sql(database_url: str) -> None:
    if not database_url or database_url.startswith("sqlite"):
        sys.exit("RLS is a Postgres feature. Set DATABASE_URL to a Postgres DSN (not sqlite).")
    try:
        from psycopg import connect
    except ImportError:
        sys.exit("psycopg is required to apply RLS. Install requirements first.")

    sql = generate_sql()
    with connect(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(sql)
        connection.commit()
    print(f"Applied RLS policies to {len(SCOPED_TABLES)} candidate tables.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", dest="print_only", action="store_true", help="Print SQL, do not apply.")
    parser.add_argument("--database-url", default=os.getenv("DATABASE_URL", ""), help="Postgres DSN.")
    args = parser.parse_args()

    if args.print_only:
        sys.stdout.write(generate_sql())
        return
    apply_sql(args.database_url)


if __name__ == "__main__":
    main()
