-- Postgres Row-Level Security tenant-isolation policies.
-- Generated by tools/apply_rls.py from SCOPED_TABLES. Idempotent; safe to re-run.
-- Apply with: python tools/apply_rls.py   (or psql -f this file)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'app_settings' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
    ALTER TABLE app_settings FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON app_settings;
    CREATE POLICY tenant_isolation ON app_settings
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'audit_logs' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON audit_logs;
    CREATE POLICY tenant_isolation ON audit_logs
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'brands' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
    ALTER TABLE brands FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON brands;
    CREATE POLICY tenant_isolation ON brands
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'categories' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
    ALTER TABLE categories FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON categories;
    CREATE POLICY tenant_isolation ON categories
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'customer_addresses' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE customer_addresses ENABLE ROW LEVEL SECURITY;
    ALTER TABLE customer_addresses FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON customer_addresses;
    CREATE POLICY tenant_isolation ON customer_addresses
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'customers' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE customers FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON customers;
    CREATE POLICY tenant_isolation ON customers
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'daily_inventory_shifts' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE daily_inventory_shifts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE daily_inventory_shifts FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON daily_inventory_shifts;
    CREATE POLICY tenant_isolation ON daily_inventory_shifts
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'daily_shift_snapshots' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE daily_shift_snapshots ENABLE ROW LEVEL SECURITY;
    ALTER TABLE daily_shift_snapshots FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON daily_shift_snapshots;
    CREATE POLICY tenant_isolation ON daily_shift_snapshots
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'delivery_orders' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE delivery_orders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE delivery_orders FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON delivery_orders;
    CREATE POLICY tenant_isolation ON delivery_orders
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'invoices' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
    ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON invoices;
    CREATE POLICY tenant_isolation ON invoices
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'locations' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE locations FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON locations;
    CREATE POLICY tenant_isolation ON locations
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'order_items' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE order_items FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON order_items;
    CREATE POLICY tenant_isolation ON order_items
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'orders' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE orders FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON orders;
    CREATE POLICY tenant_isolation ON orders
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'owner_alerts' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE owner_alerts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE owner_alerts FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON owner_alerts;
    CREATE POLICY tenant_isolation ON owner_alerts
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'payment_credentials' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE payment_credentials ENABLE ROW LEVEL SECURITY;
    ALTER TABLE payment_credentials FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON payment_credentials;
    CREATE POLICY tenant_isolation ON payment_credentials
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'payments' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
    ALTER TABLE payments FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON payments;
    CREATE POLICY tenant_isolation ON payments
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'product_variants' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
    ALTER TABLE product_variants FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON product_variants;
    CREATE POLICY tenant_isolation ON product_variants
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE products FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON products;
    CREATE POLICY tenant_isolation ON products
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'purchase_order_items' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE purchase_order_items FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON purchase_order_items;
    CREATE POLICY tenant_isolation ON purchase_order_items
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'purchase_orders' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE purchase_orders FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON purchase_orders;
    CREATE POLICY tenant_isolation ON purchase_orders
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'riders' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE riders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE riders FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON riders;
    CREATE POLICY tenant_isolation ON riders
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'sale_items' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE sale_items FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON sale_items;
    CREATE POLICY tenant_isolation ON sale_items
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'sales' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
    ALTER TABLE sales FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON sales;
    CREATE POLICY tenant_isolation ON sales
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'stock_count_items' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE stock_count_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE stock_count_items FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON stock_count_items;
    CREATE POLICY tenant_isolation ON stock_count_items
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'stock_counts' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE stock_counts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE stock_counts FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON stock_counts;
    CREATE POLICY tenant_isolation ON stock_counts
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'stock_movements' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
    ALTER TABLE stock_movements FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON stock_movements;
    CREATE POLICY tenant_isolation ON stock_movements
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'subscriptions' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON subscriptions;
    CREATE POLICY tenant_isolation ON subscriptions
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'suppliers' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE suppliers FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON suppliers;
    CREATE POLICY tenant_isolation ON suppliers
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'units' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE units ENABLE ROW LEVEL SECURITY;
    ALTER TABLE units FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON units;
    CREATE POLICY tenant_isolation ON units
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'tenant_id'
  ) THEN
    ALTER TABLE users ENABLE ROW LEVEL SECURITY;
    ALTER TABLE users FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON users;
    CREATE POLICY tenant_isolation ON users
      USING (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
      WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
             OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
  END IF;
END $$;
