"""
Single database for the whole platform.

Veyron POS (sales, sale_items, inventory, …) and eTown (customers, orders, order_items, …)
use the same connection configuration — ``DATABASE_URL`` (Postgres) or ``SQLITE_DATABASE_PATH``
(SQLite). There is no separate eTown database; all tables live in one schema.
"""

from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

try:
    from psycopg import connect as pg_connect
    from psycopg.rows import dict_row
    from psycopg.errors import IntegrityError as PostgresIntegrityError
except ImportError:
    pg_connect = None
    dict_row = None
    PostgresIntegrityError = None

from app.core.tenant.connection import TenantAwareConnection, inject_tenant_scope

BASE_DIR = Path(__file__).resolve().parents[2]
load_dotenv(BASE_DIR / ".env")

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
DEFAULT_SQLITE_DATABASE = BASE_DIR / "pos.db"
DATABASE = Path(os.getenv("SQLITE_DATABASE_PATH", str(DEFAULT_SQLITE_DATABASE)))
DATABASE_ENGINE = "postgres" if DATABASE_URL and not DATABASE_URL.startswith("sqlite") else "sqlite"


def translate_sql(sql: str) -> str:
    if DATABASE_ENGINE != "postgres":
        return sql
    translated_sql = sql.replace("INSERT OR IGNORE", "INSERT")
    translated_sql = translated_sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    translated_sql = translated_sql.replace("REAL", "DOUBLE PRECISION")
    translated_sql = re.sub(r"\?", "%s", translated_sql)
    return translated_sql


class PostgresCursorWrapper:
    def __init__(self, cursor: Any):
        self.cursor = cursor

    @property
    def rowcount(self) -> int:
        return int(self.cursor.rowcount or 0)

    def fetchone(self):
        return self.cursor.fetchone()

    def fetchall(self):
        return self.cursor.fetchall()


def _apply_rls_session(connection: Any, *, raw: bool) -> None:
    """Set the per-connection GUCs that the Postgres RLS policies read.

    Contract (see tools/apply_rls.py):
      * ``app.bypass_rls = 'on'`` grants cross-tenant access.
      * ``app.tenant_id``       scopes access to a single tenant when not bypassing.

    Bypass is granted to raw connections, super-admin requests, and any call made
    outside a Flask request context (init_db, migrations, offline scripts). A normal
    request without a resolved tenant leaves ``app.tenant_id`` empty, so RLS returns
    no rows — fail closed rather than leak across tenants.
    """
    from flask import has_request_context

    from app.core.tenant.context import current_tenant_id, is_super_admin

    bypass = True
    tenant_id: int | None = None
    if not raw and has_request_context():
        if is_super_admin():
            bypass = True
        else:
            bypass = False
            tenant_id = current_tenant_id()

    cursor = connection.cursor()
    cursor.execute("SELECT set_config('app.bypass_rls', %s, false)", ("on" if bypass else "off",))
    cursor.execute(
        "SELECT set_config('app.tenant_id', %s, false)",
        ("" if tenant_id is None else str(int(tenant_id)),),
    )


class PostgresConnectionWrapper:
    def __init__(self, dsn: str) -> None:
        self.connection = pg_connect(dsn, row_factory=dict_row)
        _apply_rls_session(self.connection, raw=False)

    def __enter__(self) -> "PostgresConnectionWrapper":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if exc_type is None:
            self.connection.commit()
        else:
            self.connection.rollback()
        self.connection.close()

    def execute(self, sql: str, params: tuple | list | None = None):
        sql, params = inject_tenant_scope(sql, params)
        cursor = self.connection.cursor()
        cursor.execute(translate_sql(sql), params or ())
        return PostgresCursorWrapper(cursor)

    def executemany(self, sql: str, seq_of_params):
        from flask import has_request_context

        from app.core.tenant.connection import inject_tenant_scope

        if not seq_of_params:
            cursor = self.connection.cursor()
            cursor.executemany(translate_sql(sql), [])
            return PostgresCursorWrapper(cursor)

        if not has_request_context():
            cursor = self.connection.cursor()
            cursor.executemany(translate_sql(sql), [tuple(p) for p in seq_of_params])
            return PostgresCursorWrapper(cursor)

        injected_sql = sql
        rows_out: list[tuple] = []
        for p in seq_of_params:
            inj_sql, inj_params = inject_tenant_scope(sql, tuple(p))
            injected_sql = inj_sql
            rows_out.append(tuple(inj_params))

        cursor = self.connection.cursor()
        cursor.executemany(translate_sql(injected_sql), rows_out)
        return PostgresCursorWrapper(cursor)

    def executescript(self, script: str):
        cursor = self.connection.cursor()
        statements = [statement.strip() for statement in script.split(";") if statement.strip()]
        for statement in statements:
            cursor.execute(translate_sql(statement))
        return PostgresCursorWrapper(cursor)


class RawPostgresConnectionWrapper:
    def __init__(self, dsn: str) -> None:
        self.connection = pg_connect(dsn, row_factory=dict_row)
        # Raw connections are the deliberate cross-tenant path (login lookups,
        # provisioning, super-admin). Grant RLS bypass explicitly.
        _apply_rls_session(self.connection, raw=True)

    def __enter__(self) -> "RawPostgresConnectionWrapper":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if exc_type is None:
            self.connection.commit()
        else:
            self.connection.rollback()
        self.connection.close()

    def execute(self, sql: str, params: tuple | list | None = None):
        cursor = self.connection.cursor()
        cursor.execute(translate_sql(sql), params or ())
        return PostgresCursorWrapper(cursor)

    def executemany(self, sql: str, seq_of_params):
        cursor = self.connection.cursor()
        cursor.executemany(translate_sql(sql), seq_of_params)
        return PostgresCursorWrapper(cursor)

    def executescript(self, script: str):
        cursor = self.connection.cursor()
        statements = [statement.strip() for statement in script.split(";") if statement.strip()]
        for statement in statements:
            cursor.execute(translate_sql(statement))
        return PostgresCursorWrapper(cursor)


def get_connection() -> Any:
    if DATABASE_ENGINE == "postgres":
        return PostgresConnectionWrapper(DATABASE_URL)

    database_path = DATABASE
    if DATABASE_URL.startswith("sqlite:///"):
        database_path = Path(DATABASE_URL.removeprefix("sqlite:///"))
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    return TenantAwareConnection(connection)


def get_raw_connection() -> Any:
    if DATABASE_ENGINE == "postgres":
        return RawPostgresConnectionWrapper(DATABASE_URL)

    database_path = DATABASE
    if DATABASE_URL.startswith("sqlite:///"):
        database_path = Path(DATABASE_URL.removeprefix("sqlite:///"))
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    return connection
